FROM amazonlinux:2

# Install Docker CLI prerequisites
RUN yum install -y docker unzip curl && yum clean all

# Install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
 && unzip awscliv2.zip \
 && ./aws/install \
 && rm -rf awscliv2.zip aws

# Verify installs
RUN aws --version && docker --version

